"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnitrollerInterface__factory = exports.IonicComptroller__factory = exports.ComptrollerStorageInterface__factory = exports.ComptrollerInterface__factory = exports.ComptrollerExtensionInterface__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ComptrollerExtensionInterface__factory_1 = require("./ComptrollerExtensionInterface__factory");
Object.defineProperty(exports, "ComptrollerExtensionInterface__factory", { enumerable: true, get: function () { return ComptrollerExtensionInterface__factory_1.ComptrollerExtensionInterface__factory; } });
var ComptrollerInterface__factory_1 = require("./ComptrollerInterface__factory");
Object.defineProperty(exports, "ComptrollerInterface__factory", { enumerable: true, get: function () { return ComptrollerInterface__factory_1.ComptrollerInterface__factory; } });
var ComptrollerStorageInterface__factory_1 = require("./ComptrollerStorageInterface__factory");
Object.defineProperty(exports, "ComptrollerStorageInterface__factory", { enumerable: true, get: function () { return ComptrollerStorageInterface__factory_1.ComptrollerStorageInterface__factory; } });
var IonicComptroller__factory_1 = require("./IonicComptroller__factory");
Object.defineProperty(exports, "IonicComptroller__factory", { enumerable: true, get: function () { return IonicComptroller__factory_1.IonicComptroller__factory; } });
var UnitrollerInterface__factory_1 = require("./UnitrollerInterface__factory");
Object.defineProperty(exports, "UnitrollerInterface__factory", { enumerable: true, get: function () { return UnitrollerInterface__factory_1.UnitrollerInterface__factory; } });
