"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SolidlyERC4626Test__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var SolidlyERC4626Test__factory_1 = require("./SolidlyERC4626Test__factory");
Object.defineProperty(exports, "SolidlyERC4626Test__factory", { enumerable: true, get: function () { return SolidlyERC4626Test__factory_1.SolidlyERC4626Test__factory; } });
