"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VoterV3__factory = exports.SolidlyLpERC4626__factory = exports.GaugeV2__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var GaugeV2__factory_1 = require("./GaugeV2__factory");
Object.defineProperty(exports, "GaugeV2__factory", { enumerable: true, get: function () { return GaugeV2__factory_1.GaugeV2__factory; } });
var SolidlyLpERC4626__factory_1 = require("./SolidlyLpERC4626__factory");
Object.defineProperty(exports, "SolidlyLpERC4626__factory", { enumerable: true, get: function () { return SolidlyLpERC4626__factory_1.SolidlyLpERC4626__factory; } });
var VoterV3__factory_1 = require("./VoterV3__factory");
Object.defineProperty(exports, "VoterV3__factory", { enumerable: true, get: function () { return VoterV3__factory_1.VoterV3__factory; } });
