"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IonicCreditDelegator__factory = exports.CreditDelegator__factory = exports.AaveCreditDelegator__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AaveCreditDelegator__factory_1 = require("./AaveCreditDelegator__factory");
Object.defineProperty(exports, "AaveCreditDelegator__factory", { enumerable: true, get: function () { return AaveCreditDelegator__factory_1.AaveCreditDelegator__factory; } });
var CreditDelegator__factory_1 = require("./CreditDelegator__factory");
Object.defineProperty(exports, "CreditDelegator__factory", { enumerable: true, get: function () { return CreditDelegator__factory_1.CreditDelegator__factory; } });
var IonicCreditDelegator__factory_1 = require("./IonicCreditDelegator__factory");
Object.defineProperty(exports, "IonicCreditDelegator__factory", { enumerable: true, get: function () { return IonicCreditDelegator__factory_1.IonicCreditDelegator__factory; } });
