"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IFundersRegistryStorage__factory = exports.IFundersRegistryExtension__factory = exports.IFundersRegistry__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IFundersRegistry__factory_1 = require("./IFundersRegistry__factory");
Object.defineProperty(exports, "IFundersRegistry__factory", { enumerable: true, get: function () { return IFundersRegistry__factory_1.IFundersRegistry__factory; } });
var IFundersRegistryExtension__factory_1 = require("./IFundersRegistryExtension__factory");
Object.defineProperty(exports, "IFundersRegistryExtension__factory", { enumerable: true, get: function () { return IFundersRegistryExtension__factory_1.IFundersRegistryExtension__factory; } });
var IFundersRegistryStorage__factory_1 = require("./IFundersRegistryStorage__factory");
Object.defineProperty(exports, "IFundersRegistryStorage__factory", { enumerable: true, get: function () { return IFundersRegistryStorage__factory_1.IFundersRegistryStorage__factory; } });
