"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IonicCErc20__factory = exports.CTokenSecondExtensionInterface__factory = exports.CTokenFirstExtensionInterface__factory = exports.CErc20StorageInterface__factory = exports.CDelegatorInterface__factory = exports.CDelegateInterface__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CDelegateInterface__factory_1 = require("./CDelegateInterface__factory");
Object.defineProperty(exports, "CDelegateInterface__factory", { enumerable: true, get: function () { return CDelegateInterface__factory_1.CDelegateInterface__factory; } });
var CDelegatorInterface__factory_1 = require("./CDelegatorInterface__factory");
Object.defineProperty(exports, "CDelegatorInterface__factory", { enumerable: true, get: function () { return CDelegatorInterface__factory_1.CDelegatorInterface__factory; } });
var CErc20StorageInterface__factory_1 = require("./CErc20StorageInterface__factory");
Object.defineProperty(exports, "CErc20StorageInterface__factory", { enumerable: true, get: function () { return CErc20StorageInterface__factory_1.CErc20StorageInterface__factory; } });
var CTokenFirstExtensionInterface__factory_1 = require("./CTokenFirstExtensionInterface__factory");
Object.defineProperty(exports, "CTokenFirstExtensionInterface__factory", { enumerable: true, get: function () { return CTokenFirstExtensionInterface__factory_1.CTokenFirstExtensionInterface__factory; } });
var CTokenSecondExtensionInterface__factory_1 = require("./CTokenSecondExtensionInterface__factory");
Object.defineProperty(exports, "CTokenSecondExtensionInterface__factory", { enumerable: true, get: function () { return CTokenSecondExtensionInterface__factory_1.CTokenSecondExtensionInterface__factory; } });
var IonicCErc20__factory_1 = require("./IonicCErc20__factory");
Object.defineProperty(exports, "IonicCErc20__factory", { enumerable: true, get: function () { return IonicCErc20__factory_1.IonicCErc20__factory; } });
