"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OraclesTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var OraclesTest__factory_1 = require("./OraclesTest__factory");
Object.defineProperty(exports, "OraclesTest__factory", { enumerable: true, get: function () { return OraclesTest__factory_1.OraclesTest__factory; } });
