"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IFlashLoanReceiver__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "function",
        name: "receiveFlashLoan",
        inputs: [
            {
                name: "borrowedAsset",
                type: "address",
                internalType: "address",
            },
            {
                name: "borrowedAmount",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "premium",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "data",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
];
class IFlashLoanReceiver__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IFlashLoanReceiver__factory = IFlashLoanReceiver__factory;
