"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IFlashloanRouterStorage__factory = exports.IFlashloanRouterExtension__factory = exports.IFlashloanRouter__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IFlashloanRouter__factory_1 = require("./IFlashloanRouter__factory");
Object.defineProperty(exports, "IFlashloanRouter__factory", { enumerable: true, get: function () { return IFlashloanRouter__factory_1.IFlashloanRouter__factory; } });
var IFlashloanRouterExtension__factory_1 = require("./IFlashloanRouterExtension__factory");
Object.defineProperty(exports, "IFlashloanRouterExtension__factory", { enumerable: true, get: function () { return IFlashloanRouterExtension__factory_1.IFlashloanRouterExtension__factory; } });
var IFlashloanRouterStorage__factory_1 = require("./IFlashloanRouterStorage__factory");
Object.defineProperty(exports, "IFlashloanRouterStorage__factory", { enumerable: true, get: function () { return IFlashloanRouterStorage__factory_1.IFlashloanRouterStorage__factory; } });
